#!usr/bin/env bash
# Configure an nginx server to listen to port 80.

# Create a symbolic link (-s option between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
